using System.Collections.Generic;

namespace Nop.Plugin.Marketplace.Core.Events
{
    public class SettlementRequestedEvent
    {
        public int EscrowTransactionId { get; set; }
        public int DropshipFulfillmentId { get; set; }

        // Who gets what
        public int SupplierVendorId { get; set; }
        public decimal SupplierAmount { get; set; }

        public int ResellerVendorId { get; set; }
        public decimal ResellerAmount { get; set; }

        public decimal PlatformFeeAmount { get; set; }

        // This MUST be generated by Escrow and passed to Wallet to guarantee idempotency!
        public string IdempotencyKey { get; set; }
    }
}